version: "3"
services:
  db:
    image: pgvector/pgvector:pg15
    container_name: n8n_postgres
    restart: always
    environment:
      - POSTGRES_USER=n8n                # Database username
      - POSTGRES_PASSWORD=n8npass        # Database user password
      - POSTGRES_DB=n8n                  # Database name
    volumes:
      - /root/app/volume/postgres:/var/lib/postgresql/data   # Persist PostgreSQL data

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_app
    restart: always
    ports:
      - "5678:5678"
    depends_on:
      - db
    environment:
      - N8N_HOST=n8n.potatodeveloper.online
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.potatodeveloper.online    # External URL for n8n (for webhooks)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - NODE_ENV=production
    # No ports exposed here; n8n is accessible only through the reverse proxy
    volumes:
      - /root/app/volume/n8n:/home/node/.n8n   # Persist n8n configuration and data

#  nginx:
#    image: nginx:alpine
#    container_name: n8n_nginx
#    restart: always
#    depends_on:
#      - n8n
#    ports:
#      - "80:80"    # HTTP
#      - "443:443"  # HTTPS
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro   # Nginx configuration for n8n
#      - ./certbot/www/:/var/www/certbot:ro               # Webroot for Certbot challenges
#      - ./certbot/conf/:/etc/letsencrypt:ro              # SSL certificates storage (Let’s Encrypt)

#  certbot:
#    image: certbot/certbot:latest
#    container_name: n8n_certbot
#    depends_on:
#      - nginx
#    volumes:
#      - ./certbot/www/:/var/www/certbot:rw                # Share challenge webroot with Nginx (rw by default)
#      - ./certbot/conf/:/etc/letsencrypt:rw               # Share certificate storage with Nginx (rw)
#    command: certonly --webroot --webroot-path /var/www/certbot --email badrus@potatodeveloper.online --agree-tos --no-eff-email -d n8n.potatodeveloper.online --dry-run
    # This service obtains/renews the Let's Encrypt certificate. Run it manually as needed.
    # It is not set to restart always, since it exits after obtaining the certificates.