version: '3.8'
services:
  db:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_DATABASE: <database name>
      MYSQL_USER: <default user>
      MYSQL_PASSWORD: <user password>
      MYSQL_ROOT_PASSWORD: <root password>
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306