version: '3'

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: 'yxofpyKM26mR33l'
      MINIO_ROOT_PASSWORD: 'yxofpyKM26mR33l'
    command: server /data --console-address ":9001"
