version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - '/Users/badrusshoolehk/Documents/riset/docker/kafka/volume/zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - database

  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    ports:
      - '9092:9092'
    volumes:
      - '/Users/badrusshoolehk/Documents/riset/docker/kafka/volume/kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LOG_DIRS=/bitnami/kafka/data # Set the log directory
      - KAFKA_LOG_FILE=/bitnami/kafka/data/kafka.log # Set the log file
      - KAFKA_LOG_LEVEL=DEBUG
    networks:
      - database
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8085:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - database
    depends_on:
      - kafka

networks:
  database:
    driver: bridge
